enableGlobalCache: true

nodeLinker: node-modules
nmMode: classic
npmScopes:
  iroha2:
    npmRegistryServer: "https://nexus.iroha.tech/repository/npm-group/"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
